name: CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Run tests
      run: |
        python my_tests.py


    - name: Check test results
      id: test-results
      run: |
        if python -m pytest; then
          echo "::set-output name=status::success"
        else
          echo "::set-output name=status::failure"
          echo "::error::Tests failed, please check the logs."
          exit 1
        fi

    - name: Approve on success
      if: steps.test-results.outputs.status == 'success'
      run: |
        echo "Tests passed. Approving the changes."
        

    - name: Reject on failure
      if: steps.test-results.outputs.status == 'failure'
      run: |
        echo "Tests failed. Rejecting the changes."
        


